[package]
name = "BevyBoids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
uid = "0.1.7"
bevy_egui = "0.17.1"
bevy_prototype_lyon = "0.7.2"
rand = "0.8.5"
